// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBL_Ze9kq1IEP43KtAh6u72o7_y7FtlE4',
    appId: '1:657082849503:web:3a0440ab2c91efbba0f16a',
    messagingSenderId: '657082849503',
    projectId: 'safe-route-b99cf',
    authDomain: 'safe-route-b99cf.firebaseapp.com',
    storageBucket: 'safe-route-b99cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0BRmbOPVGIpazpjMcKIDFvFa-rfIHk3c',
    appId: '1:657082849503:android:5e80ea1d41c18ac3a0f16a',
    messagingSenderId: '657082849503',
    projectId: 'safe-route-b99cf',
    storageBucket: 'safe-route-b99cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4GLK6MVoqrHvM3lWAMqwQK8XQjfiObU',
    appId: '1:657082849503:ios:d0a07e30ac9d06bda0f16a',
    messagingSenderId: '657082849503',
    projectId: 'safe-route-b99cf',
    storageBucket: 'safe-route-b99cf.firebasestorage.app',
    iosBundleId: 'com.example.safeRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4GLK6MVoqrHvM3lWAMqwQK8XQjfiObU',
    appId: '1:657082849503:ios:d0a07e30ac9d06bda0f16a',
    messagingSenderId: '657082849503',
    projectId: 'safe-route-b99cf',
    storageBucket: 'safe-route-b99cf.firebasestorage.app',
    iosBundleId: 'com.example.safeRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBL_Ze9kq1IEP43KtAh6u72o7_y7FtlE4',
    appId: '1:657082849503:web:b1d52a89b66cb581a0f16a',
    messagingSenderId: '657082849503',
    projectId: 'safe-route-b99cf',
    authDomain: 'safe-route-b99cf.firebaseapp.com',
    storageBucket: 'safe-route-b99cf.firebasestorage.app',
  );
}
